# @format

theme: jekyll-theme-chirpy

include:
  - "*.md"
  - "**/*.md"

title: Documentation
baseurl: ""

author:
  name: Hoang
  
avatar: https://lh3.googleusercontent.com/a/ACg8ocKJNuXz0PUktDNYhtVdP_bq5-ZEdWMTWyYeZTXp-LPGEfcp-OiV=s360-c-no