# @format

theme: jekyll-theme-chirpy

include:
  - "*.md"
  - "**/*.md"

title: Documentation
baseurl: ""
search:
  provider: lunr
  lunr:
    dir: assets/js
author:
  name: Hoang
github:
  username: nhh0718

social:
  email: hoangnh0718@gmail.com

avatar: https://lh3.googleusercontent.com/a/ACg8ocKJNuXz0PUktDNYhtVdP_bq5-ZEdWMTWyYeZTXp-LPGEfcp-OiV=s360-c-no
